<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:tns1="http://www.vertexinc.com/oseries/services/CalculateTax60"
    xmlns:vev="urn:vertexinc:o-series:tps:6:0"
    xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.vertexinc.com/oseries/services/CalculateTax60">
    <wsdl:types>
        <xsd:schema>
            <xsd:import namespace="urn:vertexinc:o-series:tps:6:0" schemaLocation="../xsd/6.0/VertexInc_Envelope.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="calculateTaxRequest">
        <wsdl:part element="vev:VertexEnvelope" name="part"/>
    </wsdl:message>
    <wsdl:message name="calculateTaxResponse">
        <wsdl:part element="vev:VertexEnvelope" name="VertexEnvelope"/>
    </wsdl:message>
    <wsdl:portType name="CalculateTaxWS60">
        <wsdl:operation name="calculateTax60">
            <wsdl:input message="tns1:calculateTaxRequest" name="calculateTaxRequest"/>
            <wsdl:output message="tns1:calculateTaxResponse" name="calculateTaxResponse"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="CalculateTax60SoapBinding" type="tns1:CalculateTaxWS60">
        <wsdlsoap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="calculateTax60">
            <wsdlsoap:operation soapAction=""/>
            <wsdl:input name="calculateTaxRequest">
                <wsdlsoap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="calculateTaxResponse">
                <wsdlsoap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="CalculateTaxWSService60">
        <wsdl:port binding="tns1:CalculateTax60SoapBinding" name="CalculateTax60">
            <wsdlsoap:address location="https://kindsnacks.ondemand.vertexinc.com:443/vertex-ws/services/CalculateTax60"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>